algoritmo "semnome"
// Função :
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var

num1:inteiro
num2:inteiro

inicio

escreval("digite um numero")
leia(num1)
escreval("digite outro numero")
leia(num2)
escreval("")

se (num1 > num2) entao
escreval(numpcarac(num1)," é maior que",num2)
fimse

se (num1 = num2) entao
escreval(numpcarac(num1)," é igual a",num2)
fimse

se (num2 > num1) entao
escreval(numpcarac(num2)," é maior que",num1)
fimse

fimalgoritmo
