algoritmo "semnome"
// Função :
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var

num1:real
num2:real

inicio

escreval("digite um numero")
leia(num1)
escreval("digite outro numero")
leia(num2)
escreval("")

escreva("o maior numero é")

se (num1 > num2) entao
escreval(num1)
fimse

se (num1 = num2) entao
escreval(num1)
fimse

se (num2 > num1) entao
escreval(num2)
fimse

fimalgoritmo
