algoritmo "semnome"

var

n : inteiro
x : real
contagem : inteiro

inicio

   escreva("Digite um numero real: ")
   leia(x)

   repita
      limpatela
      escreval("Digite um numreo real:", x)
      escreva("Digite um numero natural: ")
      leia(n)
   ate (n > 0)
   
   escreval("")
   para contagem de 1 ate n faca
      escreval("a potencia de ",numpcarac(x),"^",numpcarac(contagem)," é:", x^contagem)
   fimpara

fimalgoritmo
