algoritmo "semnome"
// Função :
// Autor :
// Data : 19/04/2022
// Seção de Declarações 
var

valor:real
valor_com_virgula:real
valor_sem_virgula:real
virgula:real

inicio

valor <- 1234
escreval(valor)

valor_com_virgula <- valor / 100
escreval(valor_com_virgula)

valor_sem_virgula <- valor_com_virgula:1:5
escreval(valor_com_virgula)

virgula <- valor_com_virgula - valor_sem_virgula
escreval(virgula)

fimalgoritmo
