algoritmo "semnome"
// Função :
// Autor :
// Data : 19/04/2022
// Seção de Declarações 
var

time:caracter

inicio

escreva("Entre com o nomde de um time de futebol: ")
leia(time)
escolha time
   caso "Flamengo","Fluminense","Vasco","Botafogo"
    escreval("É um time carioca.")
   caso "São Paulo","Palmeiras","Santos","Corinthians"
    escreval("É um time paulista.")
   outrocaso
    escreval("É de outro estado.")
fimescolha

fimalgoritmo
