algoritmo "atv 4"
// Função : soma de cubos
// Autor : David Luiz
// Data : 16/03/2022

var

A:inteiro
A2:real

B:inteiro
B2:real

C:inteiro
C2:real

R:real

inicio

escreva("Informe um valor inteiro: ")
leia(A)

escreva("Informe um outro valor inteiro: ")
leia(B)

escreva("Informe mais um valor inteiro: ")
leia(C)

A2 <- (A^3)
B2 <- (B^3)
C2 <- (C^3)
R <- A2 + B2 + C2

escreval("A soma do cubo dos tres valores é:",R)

fimalgoritmo
