algoritmo "semnome"
// Função :
// Autor :
// Data : 15/03/2022
// Seção de Declarações 
var

comprimento:real
largura:real
altura:real
resultado:real

inicio

escreval("Informe o comprimento da caixa em meteros:")
leia(comprimento)
escreval("Informe a largura da caixa em meteros:")
leia(largura)
escreval("Informe a altura da caixa em meteros:")
leia(altura)

resultado <- comprimento * largura * altura

escreval("o volume da caixa é de ",resultado,"m3")

fimalgoritmo
