algoritmo "Primeiro"
// Função : Familiarizar com o ambiente VisualG
// Autor : David Luiz Vinhal
// Data : 23/02/2022
// Seção de Declarações
var

inicio
      //Seção De Comandos
      
      escreval ("Olá Mundo.")
      escreval ("Eu vou aprender a programar computadores")
      
      //Aperte a tecla F9 para executar
      
      //Depois a tecla "Esc" para retorna ao VisualG
fimalgoritmo
